### ISSUE TITLE
User authentication and db access over user token

### ISSUE THREAD

**Issue by vcarlucci** [sammychinedu2ky/blazorfirestore#1]
Hi @sammychinedu2ky , I found your great article to setup firebase in blazor [here](https://swacblooms.com/using-cloud-firestore-in-blazor-webassembly/). What I would like to learn is now, set up a firebase db, user authentication and have both on a blazor webassembly with secured db access over a authenticated token of course. 

-> If the user is not logged in already it will be redirected to the login/registration first before acessing the blazor wasm. 
-> Show user mail on header when logged in
-> Log out button with redirect to a custom link
-> Pages secured with authentication injection something like : @attribute [Authorize] ?

Would be great to get something like this, because this would be a more complete setup example.. 

Thank you!

**Comment by sammychinedu2ky** [comment]
Thanks @vcarlucci. Using firebase on the client side is secured once you add the origin to the list of accepted  domains that could access firebase.
Since I chose the client side route of blazor, I would have to write some functions to illustrate how to asynchronously check the authentication state of the user before rendering the actual information. For instance a loader might be rendered while a blazor lifecycle function checks if the user is authenticated or not. If the user is not authenticated, a redirect could occur thereby sending the user to the login page.

**Comment by sammychinedu2ky** [comment]
If time permits I could try writing an article about that but no guarantees for now.

**Comment by vcarlucci** [comment]
Thank you for your answer @sammychinedu2ky that sounds good. I would find it very exciting to see what such an approach would look like, as sooner as better :)
Found some repo here [https://github.com/cschweig2/TrailBlazor/tree/main/TrailBlazor](https://github.com/cschweig2/TrailBlazor/tree/main/TrailBlazor) which goes into that direction..

**Comment by sammychinedu2ky** [comment]
Cool 😎
